version: '3'

services:

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #     - "443:443"
  #   volumes:
  #     - ../../Www:/www/:rw,cached
  #     - ../nginx/conf/:/etc/nginx/conf.d/:ro,cached
  #     - ../log/:/var/log/nginx/:rw,cached
  #   # links:
  #   #   - php72:fpm72
  #   #   # - php56:fpm56
  #   environment:
  #     - TZ=Asia/Shanghai
  #   container_name: nginx
  #   networks:
  #     docker_net:
  #       ipv4_address: ${NGINX_IP}


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ../../Www:/var/www/html/:rw,cached
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro,cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,cached
      - ./log/nginx/:/var/log/nginx/:rw,cached
    # links:
    #   - php72:fpm72
    #   - php56:fpm56
    environment:
      - TZ=Asia/Shanghai
    networks:
      docker_net:
        ipv4_address: ${NGINX_IP}


  # php72:
  #   build: ./php/php72/
  #   expose:
  #     - "9000"
  #   volumes:
  #     - ../../Www:/www/:rw,cached
  #     - ../conf/php/php72.ini:/usr/local/etc/php/php.ini:ro,cached
  #     - ../conf/php/php-fpm.d/www72.conf:/usr/local/etc/php-fpm.d/www.conf:rw,cached
  #     - ../log/php-fpm/:/var/log/php-fpm/:rw,cached
  #   links:
  #     - mysql:mysql
  #     - redis:redis
  #   container_name: php72
  #   networks:
  #     docker_net:
  #       ipv4_address: ${PHP72_IP}

  # php56:
  #   build: ./php/php56/
  #   expose:
  #     - "9000"
  #   volumes:
  #     - ${WORKSPACES}:/var/www/html/:rw,cached
  #     - ./conf/php/php56.ini:/usr/local/etc/php/php.ini:ro,cached
  #     - ./conf/php/php-fpm.d/www56.conf:/usr/local/etc/php-fpm.d/www.conf:rw,cached
  #     - ./log/php-fpm/:/var/log/php-fpm/:rw,cached
  #   links:
  #     - mysql:mysql
  #     - redis:redis
  #   networks:
  #     docker_net:
  #       ipv4_address: ${PHP56_IP}

#   mysql:
#     image: mysql:5.7
#     ports:
#       - "3306:3306"
#     volumes:
#       - ../conf/mysql/:/etc/mysql/:ro,cached
#       - ../mysql/:/var/lib/mysql/:rw,cached
#       - ../log/mysql/:/var/log/mysql/:rw,cached
#     environment:
#       MYSQL_ROOT_PASSWORD: "123456"
#     container_name: mysql57
#     networks:
#       docker_net:
#         ipv4_address: ${MYSQL_IP}

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
#     container_name: redis
#     networks:
#       docker_net:
#         ipv4_address: ${REDIS_IP}

#   portainer:
#     image: portainer/portainer:latest
#     ports:
#       - "9000:9000"
#     volumes:
#       - ../run/docker.sock:/var/run/docker.sock:cached
#       - ../portainer/:/data:cached
#     container_name: portainer
#     networks:
#       docker_net:
#         ipv4_address: ${PORTAINER_IP}
  
#   memcached:
#     image: memcached:1.5.11-alpine
#     ports:
#       - "11211:11211"
#       - "11212:11212"
#       - "11213:11213"
#     container_name: memcached
#     networks:
#         docker_net:
#           ipv4_address: ${MEMCACHED_IP}

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: "${DOCKER_SUBNET}"